#!/bin/bash
#
# Script used to update the istex-view version in the docker-compose.yml
# called from npm version <patch|minor|major> (see package.json)
# $npm_package_version is filled by "npm version" stuff
# see https://docs.npmjs.com/misc/scripts
#

set -e

echo "---> Patching docker-compose.yml (prod file) for using this version ${npm_package_version}"
sed -i "s#\(image: istex/istex-view:\)\([\.a-z0-9]\+\)#\1${npm_package_version}#g" docker-compose.yml
echo "---> Patching README.md with the right prod version ${npm_package_version}"
sed -i "s#\(istex/istex-view:\)\([\.a-z0-9]\+\)#\1${npm_package_version}#g" README.md
git add docker-compose.yml
